### ISSUE TITLE
Update xeofs v3 

### ISSUE THREAD

**Issue by nicrie** [ProjectPythia/eofs-cookbook#15]
:wave: xeofs dev here! I’m a big fan of Project Pythia, so I’m especially happy to see that xeofs is useful for your work. Since we recently released version 3, which includes [some breaking changes](https://xeofs.readthedocs.io/en/latest/content/user_guide/migration_v3.html), I thought it may be helpful to give you a heads up & what to do to make your notebook compatible with the new version:

- The `EOF` class is now accessed via `xe.single.EOF`, instead of `xe.models.EOF`.
- The default value for `normalize` in the PC `scores` is now `False`. To get the same result as before, you’ll need to explicitly set `model.scores(normalize=True)`.

Hope it helps!

**Comment by r-ford** [comment]
Thanks for the update (and for developing such a useful package)!

**Comment by brian-rose** [comment]
Looks like this update does indeed break some code in this cookbook. The build is currently failing with
```
AttributeError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 s_model = xe.models.EOF(n_modes=4, use_coslat=True)
      2 s_model.fit(sst, dim='time')
      3 s_eofs = s_model.components()

AttributeError: module 'xeofs' has no attribute 'models'
```
e.g. [here](https://github.com/ProjectPythia/eofs-cookbook/actions/runs/11135920353/job/30946808121#step:20:104)

**Comment by brian-rose** [comment]
(the nightly build was disabled in this repo, so it was a silent failure until just now)

**Comment by r-ford** [comment]
Completed with https://github.com/ProjectPythia/eofs-cookbook/commit/12efa2b1a1a9dd76036c971247cbba26b4f4120d.
