### ISSUE TITLE
Nightly builds failing for a couple months

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/eofs-cookbook#17]
**What happened**:

Dear authors and/or contributors (cc'ing @r-ford), the nightly builds of this cookbook have been failing for the last couple months. 

Could you please have a look at it?

**Minimal Complete Verifiable Example**:

[Latest nightly build](https://github.com/ProjectPythia/eofs-cookbook/actions/runs/11376642042/job/31649448487) as of the creation of this issue.

**Anything else we need to know?**:

If you think it is due to Pythia infrastructure or something else other than the cookbook itself, please let us know.

**Comment by r-ford** [comment]
Thanks! This is the result of #15.

**Comment by erogluorhan** [comment]
Thanks for pointing out!

**Comment by r-ford** [comment]
Completed with https://github.com/ProjectPythia/eofs-cookbook/commit/12efa2b1a1a9dd76036c971247cbba26b4f4120d.
